export enum COMMUNICATION_CONSTANTS {
  REFRESH_CARD_ID = 'refreshCard',
  SAVE_DEPENDENCIES_ID = 'saveDependencies',
  RENDER_DEPENDENCIES_ID = 'renderDependencies',
  RELOAD_EXTENSION_ID = 'reloadExtension',
}

export enum BUTTON_TEXTS {
  ADD_DEPENDENCY = 'ADD DEPENDENCY',
  DEPENDANT = 'DEPENDANT',
  SET_AS_PARENT = 'SET_AS_PARENT',
  SHOW_DEPENDENCIES = 'SHOW_DEPENDENCIES',
}
